// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG4FpVrc_Ia5UgMsMHZlkzVusFRhhXjL8',
    appId: '1:719821557414:web:8b285ef435dee76b38ee67',
    messagingSenderId: '719821557414',
    projectId: 'parkour-jakarta-15-anniv',
    authDomain: 'parkour-jakarta-15-anniv.firebaseapp.com',
    storageBucket: 'parkour-jakarta-15-anniv.appspot.com',
    measurementId: 'G-QTCKSRFFBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbhs4m8zZPQNFkJBhM0UxV8-LUuHlubBw',
    appId: '1:719821557414:android:292f18ec484a1f3f38ee67',
    messagingSenderId: '719821557414',
    projectId: 'parkour-jakarta-15-anniv',
    storageBucket: 'parkour-jakarta-15-anniv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_hOZDa31Jt7EjI_PWuvWXXFRS4zyee94',
    appId: '1:719821557414:ios:117ef9d31e7bd29338ee67',
    messagingSenderId: '719821557414',
    projectId: 'parkour-jakarta-15-anniv',
    storageBucket: 'parkour-jakarta-15-anniv.appspot.com',
    iosClientId: '719821557414-f5t13qdv7chqn9095noqq1hfhcnbf5bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.websiteParkourjkt',
  );
}
